version: 2

jobs:
  build:
    machine:
        enabled: true
    steps:
      - run:
          name: Install Nix
          command: |
            sudo mkdir -p /nix
            sudo chown circleci /nix
            bash <(curl https://nixos.org/nix/install)
            echo '. /home/circleci/.nix-profile/etc/profile.d/nix.sh' >> $BASH_ENV
            sudo mkdir -p /etc/nix

            # Enable sandbox
            echo "build-use-sandbox = true" | sudo tee -a /etc/nix/nix.conf

      - checkout

      - run:
          name: Build
          command: |
            nix-build --no-link --sandbox --max-jobs 20
            build_dir=$(nix-build --no-link)
            mkdir -p /tmp/artifacts
            cp -r "$build_dir"/* /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts

      - run:
          name: "Update Node.js and npm (master only)"
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
                nix-env -f ./nix -iA nodejs-8_x
            fi

      - run:
          name: "Install netlify-cli (master only)"
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
                npm install netlify-cli
            fi

      - run:
          name: "Netlify deploy (master only)"
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
                echo "Deploying to production"
                ./node_modules/netlify-cli/bin/run deploy \
                    --dir=$(nix-build --no-link) \
                    --message="$CIRCLE_SHA1" --prod
            fi

workflows:
  version: 2
  build:
    jobs:
      - build
