version: 2

jobs:
  build:
    machine:
        enabled: true
    steps:
      - run:
          name: Install Nix
          command: |
            sudo mkdir -p /nix
            sudo chown circleci /nix
            bash <(curl https://nixos.org/nix/install)
            echo '. /home/circleci/.nix-profile/etc/profile.d/nix.sh' >> $BASH_ENV
            sudo mkdir -p /etc/nix

            # Enable sandbox
            echo "build-use-sandbox = true" | sudo tee -a /etc/nix/nix.conf

      - run:
          name: "Update Node.js and npm"
          command: |
            nix-env -f ./nix -iA nodejs-10_x

      - run:
          name: Install netlify-cli
          command: |
            npm install netlify-cli

      - checkout

      - run:
          name: Netlify deploy
          command: |
            echo "Branch:" "$CIRCLE_BRANCH"
            echo "Repo:" "$CIRCLE_REPOSITORY_URL"
            echo "PR:" "$CIRCLE_PULL_REQUEST"
            if [ "$CIRCLE_BRANCH" == "master" ]; then
                echo "Deploying to production"
                ./node_modules/netlify-cli/bin/run deploy \
                    --dir=$(nix-build --no-link) \
                    --message="$CIRCLE_SHA1" --prod
            elif [ -n "$CIRCLE_PULL_REQUEST" ]; then
                echo "One time deploy for PR $CIRCLE_PR_NUMBER"
                ./node_modules/netlify-cli/bin/run deploy \
                    --dir=$(nix-build --no-link) \
                    --message="$CIRCLE_SHA1"
            else
                echo "Not deploying"
            fi

workflows:
  version: 2
  build:
    jobs:
      - build
